package com.ifscfinder.domain.catalog

data class IfscBranch(
    val ifsc: String,
    val bankName: String,
    val branch: String,
    val city: String,
    val state: String
)

object IFSCBankCatalog {
    val branches: List<IfscBranch> = listOf(
        IfscBranch("SBIN0000300", "State Bank of India", "New Delhi Main Branch", "New Delhi", "Delhi"),
        IfscBranch("SBIN0000590", "State Bank of India", "Bangalore City", "Bangalore", "Karnataka"),
        IfscBranch("SBIN0001707", "State Bank of India", "Chennai Main Branch", "Chennai", "Tamil Nadu"),
        IfscBranch("SBIN0001506", "State Bank of India", "Kolkata Main Branch", "Kolkata", "West Bengal"),
        IfscBranch("SBIN0004555", "State Bank of India", "Pune Camp", "Pune", "Maharashtra"),
        IfscBranch("SBIN0003785", "State Bank of India", "Ahmedabad Main", "Ahmedabad", "Gujarat"),
        IfscBranch("SBIN0001037", "State Bank of India", "Hyderabad Main", "Hyderabad", "Telangana"),
        IfscBranch("SBIN0004266", "State Bank of India", "Bandra West", "Mumbai", "Maharashtra"),
        IfscBranch("SBIN0000058", "State Bank of India", "Mumbai Main Branch", "Mumbai", "Maharashtra"),
        IfscBranch("SBIN0003925", "State Bank of India", "Lucknow Main", "Lucknow", "Uttar Pradesh"),
        IfscBranch("SBIN0006603", "State Bank of India", "Jaipur Main", "Jaipur", "Rajasthan"),
        IfscBranch("SBIN0002080", "State Bank of India", "Chandigarh Main", "Chandigarh", "Chandigarh"),
        IfscBranch("SBIN0000014", "State Bank of India", "Fort Mumbai", "Mumbai", "Maharashtra"),
        IfscBranch("SBIN0001067", "State Bank of India", "Bhubaneswar Main", "Bhubaneswar", "Odisha"),
        IfscBranch("SBIN0000122", "State Bank of India", "Patna Main", "Patna", "Bihar"),
        IfscBranch("SBIN0000041", "State Bank of India", "Indore Main", "Indore", "Madhya Pradesh"),
        IfscBranch("SBIN0000213", "State Bank of India", "Nagpur Main", "Nagpur", "Maharashtra"),
        IfscBranch("SBIN0000240", "State Bank of India", "Thiruvananthapuram Main", "Thiruvananthapuram", "Kerala"),
        IfscBranch("SBIN0000071", "State Bank of India", "Guwahati Main", "Guwahati", "Assam"),
        IfscBranch("SBIN0000149", "State Bank of India", "Ranchi Main", "Ranchi", "Jharkhand"),
        IfscBranch("HDFC0000001", "HDFC Bank", "Fort", "Mumbai", "Maharashtra"),
        IfscBranch("HDFC0000060", "HDFC Bank", "Connaught Place", "New Delhi", "Delhi"),
        IfscBranch("HDFC0000080", "HDFC Bank", "Bangalore", "Bangalore", "Karnataka"),
        IfscBranch("HDFC0000120", "HDFC Bank", "Chennai", "Chennai", "Tamil Nadu"),
        IfscBranch("HDFC0000020", "HDFC Bank", "Kolkata", "Kolkata", "West Bengal"),
        IfscBranch("HDFC0000070", "HDFC Bank", "Hyderabad", "Hyderabad", "Telangana"),
        IfscBranch("HDFC0000129", "HDFC Bank", "Ahmedabad", "Ahmedabad", "Gujarat"),
        IfscBranch("HDFC0000115", "HDFC Bank", "Pune", "Pune", "Maharashtra"),
        IfscBranch("HDFC0000147", "HDFC Bank", "Jaipur", "Jaipur", "Rajasthan"),
        IfscBranch("HDFC0000271", "HDFC Bank", "Lucknow", "Lucknow", "Uttar Pradesh"),
        IfscBranch("HDFC0000240", "HDFC Bank", "Chandigarh", "Chandigarh", "Chandigarh"),
        IfscBranch("HDFC0000153", "HDFC Bank", "Bhubaneswar", "Bhubaneswar", "Odisha"),
        IfscBranch("HDFC0000160", "HDFC Bank", "Patna", "Patna", "Bihar"),
        IfscBranch("HDFC0000170", "HDFC Bank", "Indore", "Indore", "Madhya Pradesh"),
        IfscBranch("HDFC0000180", "HDFC Bank", "Nagpur", "Nagpur", "Maharashtra"),
        IfscBranch("HDFC0000190", "HDFC Bank", "Kochi", "Kochi", "Kerala"),
        IfscBranch("HDFC0000200", "HDFC Bank", "Guwahati", "Guwahati", "Assam"),
        IfscBranch("HDFC0000210", "HDFC Bank", "Ranchi", "Ranchi", "Jharkhand"),
        IfscBranch("HDFC0000220", "HDFC Bank", "Coimbatore", "Coimbatore", "Tamil Nadu"),
        IfscBranch("HDFC0000230", "HDFC Bank", "Visakhapatnam", "Visakhapatnam", "Andhra Pradesh"),
        IfscBranch("ICIC0000001", "ICICI Bank", "Nariman Point", "Mumbai", "Maharashtra"),
        IfscBranch("ICIC0000002", "ICICI Bank", "MG Road", "Bangalore", "Karnataka"),
        IfscBranch("ICIC0000003", "ICICI Bank", "Delhi", "New Delhi", "Delhi"),
        IfscBranch("ICIC0000004", "ICICI Bank", "Chennai", "Chennai", "Tamil Nadu"),
        IfscBranch("ICIC0000005", "ICICI Bank", "Kolkata", "Kolkata", "West Bengal"),
        IfscBranch("ICIC0000031", "ICICI Bank", "Pune", "Pune", "Maharashtra"),
        IfscBranch("ICIC0000022", "ICICI Bank", "Hyderabad", "Hyderabad", "Telangana"),
        IfscBranch("ICIC0000011", "ICICI Bank", "Ahmedabad", "Ahmedabad", "Gujarat"),
        IfscBranch("ICIC0000041", "ICICI Bank", "Jaipur", "Jaipur", "Rajasthan"),
        IfscBranch("ICIC0000051", "ICICI Bank", "Lucknow", "Lucknow", "Uttar Pradesh"),
        IfscBranch("ICIC0000061", "ICICI Bank", "Chandigarh", "Chandigarh", "Chandigarh"),
        IfscBranch("ICIC0000071", "ICICI Bank", "Indore", "Indore", "Madhya Pradesh"),
        IfscBranch("ICIC0000081", "ICICI Bank", "Nagpur", "Nagpur", "Maharashtra"),
        IfscBranch("ICIC0000091", "ICICI Bank", "Kochi", "Kochi", "Kerala"),
        IfscBranch("ICIC0000101", "ICICI Bank", "Coimbatore", "Coimbatore", "Tamil Nadu"),
        IfscBranch("ICIC0000111", "ICICI Bank", "Patna", "Patna", "Bihar"),
        IfscBranch("ICIC0000121", "ICICI Bank", "Bhubaneswar", "Bhubaneswar", "Odisha"),
        IfscBranch("UTIB0000001", "Axis Bank", "Mumbai", "Mumbai", "Maharashtra"),
        IfscBranch("UTIB0000002", "Axis Bank", "Delhi", "New Delhi", "Delhi"),
        IfscBranch("UTIB0000003", "Axis Bank", "Bangalore", "Bangalore", "Karnataka"),
        IfscBranch("UTIB0000022", "Axis Bank", "Chennai", "Chennai", "Tamil Nadu"),
        IfscBranch("UTIB0000123", "Axis Bank", "Pune", "Pune", "Maharashtra"),
        IfscBranch("UTIB0000031", "Axis Bank", "Hyderabad", "Hyderabad", "Telangana"),
        IfscBranch("UTIB0000103", "Axis Bank", "Kolkata", "Kolkata", "West Bengal"),
        IfscBranch("UTIB0000041", "Axis Bank", "Ahmedabad", "Ahmedabad", "Gujarat"),
        IfscBranch("UTIB0000051", "Axis Bank", "Jaipur", "Jaipur", "Rajasthan"),
        IfscBranch("UTIB0000061", "Axis Bank", "Lucknow", "Lucknow", "Uttar Pradesh"),
        IfscBranch("UTIB0000071", "Axis Bank", "Chandigarh", "Chandigarh", "Chandigarh"),
        IfscBranch("UTIB0000081", "Axis Bank", "Indore", "Indore", "Madhya Pradesh"),
        IfscBranch("UTIB0000091", "Axis Bank", "Nagpur", "Nagpur", "Maharashtra"),
        IfscBranch("UTIB0000111", "Axis Bank", "Kochi", "Kochi", "Kerala"),
        IfscBranch("UTIB0000131", "Axis Bank", "Coimbatore", "Coimbatore", "Tamil Nadu"),
        IfscBranch("PUNB0465200", "Punjab National Bank", "Connaught Place", "New Delhi", "Delhi"),
        IfscBranch("PUNB0122000", "Punjab National Bank", "Mumbai Fort", "Mumbai", "Maharashtra"),
        IfscBranch("PUNB0019000", "Punjab National Bank", "Kolkata Main", "Kolkata", "West Bengal"),
        IfscBranch("PUNB0512000", "Punjab National Bank", "Bangalore", "Bangalore", "Karnataka"),
        IfscBranch("PUNB0060000", "Punjab National Bank", "Chennai", "Chennai", "Tamil Nadu"),
        IfscBranch("PUNB0063000", "Punjab National Bank", "Hyderabad", "Hyderabad", "Telangana"),
        IfscBranch("PUNB0039000", "Punjab National Bank", "Ahmedabad", "Ahmedabad", "Gujarat"),
        IfscBranch("PUNB0049000", "Punjab National Bank", "Pune", "Pune", "Maharashtra"),
        IfscBranch("PUNB0059000", "Punjab National Bank", "Jaipur", "Jaipur", "Rajasthan"),
        IfscBranch("PUNB0079000", "Punjab National Bank", "Lucknow", "Lucknow", "Uttar Pradesh"),
        IfscBranch("BARB0BANGAL", "Bank of Baroda", "Basavanagudi", "Bangalore", "Karnataka"),
        IfscBranch("BARB0MGROAD", "Bank of Baroda", "MG Road", "Mumbai", "Maharashtra"),
        IfscBranch("BARB0DELHX", "Bank of Baroda", "Delhi Main", "New Delhi", "Delhi"),
        IfscBranch("BARB0POWAI", "Bank of Baroda", "Powai", "Mumbai", "Maharashtra"),
        IfscBranch("BARB0AHMED", "Bank of Baroda", "Ahmedabad Main", "Ahmedabad", "Gujarat"),
        IfscBranch("BARB0KOLKAT", "Bank of Baroda", "Kolkata Main", "Kolkata", "West Bengal"),
        IfscBranch("BARB0CHENNA", "Bank of Baroda", "Chennai Main", "Chennai", "Tamil Nadu"),
        IfscBranch("BARB0HYDERA", "Bank of Baroda", "Hyderabad Main", "Hyderabad", "Telangana"),
        IfscBranch("BARB0PUNEXX", "Bank of Baroda", "Pune Camp", "Pune", "Maharashtra"),
        IfscBranch("BARB0JAIPUR", "Bank of Baroda", "Jaipur Main", "Jaipur", "Rajasthan"),
        IfscBranch("CNRB0000001", "Canara Bank", "Head Office", "Bangalore", "Karnataka"),
        IfscBranch("CNRB0000032", "Canara Bank", "Mumbai Fort", "Mumbai", "Maharashtra"),
        IfscBranch("CNRB0000240", "Canara Bank", "Connaught Place", "New Delhi", "Delhi"),
        IfscBranch("CNRB0000789", "Canara Bank", "Chennai Main", "Chennai", "Tamil Nadu"),
        IfscBranch("CNRB0002262", "Canara Bank", "Hyderabad Main", "Hyderabad", "Telangana"),
        IfscBranch("CNRB0004792", "Canara Bank", "Pune Main", "Pune", "Maharashtra"),
        IfscBranch("CNRB0004637", "Canara Bank", "Ahmedabad Main", "Ahmedabad", "Gujarat"),
        IfscBranch("CNRB0001234", "Canara Bank", "Kolkata Main", "Kolkata", "West Bengal"),
        IfscBranch("CNRB0003456", "Canara Bank", "Jaipur Main", "Jaipur", "Rajasthan"),
        IfscBranch("CNRB0005678", "Canara Bank", "Lucknow Main", "Lucknow", "Uttar Pradesh"),
        IfscBranch("KKBK0000001", "Kotak Mahindra Bank", "Nariman Point", "Mumbai", "Maharashtra"),
        IfscBranch("KKBK0000261", "Kotak Mahindra Bank", "New Delhi", "New Delhi", "Delhi"),
        IfscBranch("KKBK0008101", "Kotak Mahindra Bank", "Bangalore", "Bangalore", "Karnataka"),
        IfscBranch("KKBK0000958", "Kotak Mahindra Bank", "Chennai", "Chennai", "Tamil Nadu"),
        IfscBranch("KKBK0000271", "Kotak Mahindra Bank", "Hyderabad", "Hyderabad", "Telangana"),
        IfscBranch("KKBK0000811", "Kotak Mahindra Bank", "Kolkata", "Kolkata", "West Bengal"),
        IfscBranch("KKBK0000588", "Kotak Mahindra Bank", "Pune", "Pune", "Maharashtra"),
        IfscBranch("KKBK0000123", "Kotak Mahindra Bank", "Ahmedabad", "Ahmedabad", "Gujarat"),
        IfscBranch("KKBK0000456", "Kotak Mahindra Bank", "Jaipur", "Jaipur", "Rajasthan"),
        IfscBranch("KKBK0000789", "Kotak Mahindra Bank", "Lucknow", "Lucknow", "Uttar Pradesh"),
        IfscBranch("IDIB000A001", "Indian Bank", "Anna Salai", "Chennai", "Tamil Nadu"),
        IfscBranch("IDIB000B001", "Indian Bank", "Bangalore Main", "Bangalore", "Karnataka"),
        IfscBranch("IDIB000D001", "Indian Bank", "Delhi Main", "New Delhi", "Delhi"),
        IfscBranch("IDIB000M001", "Indian Bank", "Mumbai Main", "Mumbai", "Maharashtra"),
        IfscBranch("IDIB000K001", "Indian Bank", "Kolkata Main", "Kolkata", "West Bengal"),
        IfscBranch("IDIB000H001", "Indian Bank", "Hyderabad Main", "Hyderabad", "Telangana"),
        IfscBranch("IDIB000P001", "Indian Bank", "Pune Main", "Pune", "Maharashtra"),
        IfscBranch("IDIB000J001", "Indian Bank", "Jaipur Main", "Jaipur", "Rajasthan"),
        IfscBranch("UBIN0534567", "Union Bank of India", "Connaught Place", "New Delhi", "Delhi"),
        IfscBranch("UBIN0567890", "Union Bank of India", "Mumbai Main", "Mumbai", "Maharashtra"),
        IfscBranch("UBIN0532100", "Union Bank of India", "Bangalore Main", "Bangalore", "Karnataka"),
        IfscBranch("UBIN0532200", "Union Bank of India", "Chennai Main", "Chennai", "Tamil Nadu"),
        IfscBranch("UBIN0532300", "Union Bank of India", "Kolkata Main", "Kolkata", "West Bengal"),
        IfscBranch("UBIN0532400", "Union Bank of India", "Hyderabad Main", "Hyderabad", "Telangana"),
        IfscBranch("UBIN0532500", "Union Bank of India", "Ahmedabad Main", "Ahmedabad", "Gujarat"),
        IfscBranch("UBIN0532600", "Union Bank of India", "Pune Main", "Pune", "Maharashtra"),
        IfscBranch("YESB0000001", "Yes Bank", "Mumbai Main", "Mumbai", "Maharashtra"),
        IfscBranch("YESB0000002", "Yes Bank", "Delhi Main", "New Delhi", "Delhi"),
        IfscBranch("YESB0000003", "Yes Bank", "Bangalore Main", "Bangalore", "Karnataka"),
        IfscBranch("YESB0000004", "Yes Bank", "Chennai Main", "Chennai", "Tamil Nadu"),
        IfscBranch("YESB0000005", "Yes Bank", "Hyderabad Main", "Hyderabad", "Telangana"),
        IfscBranch("YESB0000006", "Yes Bank", "Kolkata Main", "Kolkata", "West Bengal"),
        IfscBranch("YESB0000007", "Yes Bank", "Pune Main", "Pune", "Maharashtra"),
        IfscBranch("YESB0000008", "Yes Bank", "Ahmedabad Main", "Ahmedabad", "Gujarat"),
        IfscBranch("INDB0000001", "IndusInd Bank", "Mumbai Main", "Mumbai", "Maharashtra"),
        IfscBranch("INDB0000002", "IndusInd Bank", "Delhi Main", "New Delhi", "Delhi"),
        IfscBranch("INDB0000003", "IndusInd Bank", "Bangalore Main", "Bangalore", "Karnataka"),
        IfscBranch("INDB0000004", "IndusInd Bank", "Chennai Main", "Chennai", "Tamil Nadu"),
        IfscBranch("INDB0000005", "IndusInd Bank", "Hyderabad Main", "Hyderabad", "Telangana"),
        IfscBranch("INDB0000006", "IndusInd Bank", "Kolkata Main", "Kolkata", "West Bengal"),
        IfscBranch("INDB0000007", "IndusInd Bank", "Pune Main", "Pune", "Maharashtra"),
        IfscBranch("INDB0000008", "IndusInd Bank", "Jaipur Main", "Jaipur", "Rajasthan"),
        IfscBranch("FDRL0000001", "Federal Bank", "Aluva Main", "Kochi", "Kerala"),
        IfscBranch("FDRL0000002", "Federal Bank", "Bangalore Main", "Bangalore", "Karnataka"),
        IfscBranch("FDRL0000003", "Federal Bank", "Chennai Main", "Chennai", "Tamil Nadu"),
        IfscBranch("FDRL0000004", "Federal Bank", "Mumbai Main", "Mumbai", "Maharashtra"),
        IfscBranch("FDRL0000005", "Federal Bank", "Delhi Main", "New Delhi", "Delhi"),
        IfscBranch("FDRL0000006", "Federal Bank", "Hyderabad Main", "Hyderabad", "Telangana"),
        IfscBranch("BKID0000001", "Bank of India", "Mumbai Main", "Mumbai", "Maharashtra"),
        IfscBranch("BKID0000002", "Bank of India", "Delhi Main", "New Delhi", "Delhi"),
        IfscBranch("BKID0000003", "Bank of India", "Bangalore Main", "Bangalore", "Karnataka"),
        IfscBranch("BKID0000004", "Bank of India", "Chennai Main", "Chennai", "Tamil Nadu"),
        IfscBranch("BKID0000005", "Bank of India", "Kolkata Main", "Kolkata", "West Bengal"),
        IfscBranch("BKID0000006", "Bank of India", "Hyderabad Main", "Hyderabad", "Telangana"),
        IfscBranch("BKID0000007", "Bank of India", "Pune Main", "Pune", "Maharashtra"),
        IfscBranch("BKID0000008", "Bank of India", "Ahmedabad Main", "Ahmedabad", "Gujarat"),
        IfscBranch("MAHB0000001", "Bank of Maharashtra", "Pune Head Office", "Pune", "Maharashtra"),
        IfscBranch("MAHB0000002", "Bank of Maharashtra", "Mumbai Main", "Mumbai", "Maharashtra"),
        IfscBranch("MAHB0000003", "Bank of Maharashtra", "Delhi Main", "New Delhi", "Delhi"),
        IfscBranch("MAHB0000004", "Bank of Maharashtra", "Bangalore Main", "Bangalore", "Karnataka"),
        IfscBranch("MAHB0000005", "Bank of Maharashtra", "Nagpur Main", "Nagpur", "Maharashtra"),
        IfscBranch("MAHB0000006", "Bank of Maharashtra", "Nashik Main", "Nashik", "Maharashtra"),
        IfscBranch("MAHB0000007", "Bank of Maharashtra", "Aurangabad Main", "Aurangabad", "Maharashtra"),
        IfscBranch("MAHB0000008", "Bank of Maharashtra", "Kolhapur Main", "Kolhapur", "Maharashtra")
    )

    fun search(query: String): List<IfscBranch> {
        val q = query.trim()
        if (q.isEmpty()) return emptyList()
        val upper = q.uppercase()
        return branches.filter { branch ->
            branch.ifsc.uppercase().startsWith(upper) ||
                branch.ifsc.equals(upper, ignoreCase = true) ||
                branch.bankName.contains(q, ignoreCase = true) ||
                branch.city.contains(q, ignoreCase = true) ||
                branch.branch.contains(q, ignoreCase = true)
        }
    }

    fun findByIfsc(ifsc: String): IfscBranch? =
        branches.find { it.ifsc.equals(ifsc, ignoreCase = true) }

    fun bankNames(): List<String> = branches.map { it.bankName }.distinct().sorted()

    fun branchesForBank(bankName: String): List<IfscBranch> =
        branches.filter { it.bankName.equals(bankName, ignoreCase = true) }
}
